sudo: required
dist: trusty

language: java

services:
  - docker

jdk: oraclejdk8

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

before_install:
  - echo "MAVEN_OPTS='-Xms1g -Xmx2g'" > ~/.mavenrc

script:
  - cd vorto-generators
  - mvn -q clean install
  - if [ -n "$TRAVIS_TAG" ]; then
    docker build --build-arg JAR_FILE=./generator-runner/target/generator-runner-3rd-party-exec.jar -f docker/Generators_Dockerfile -t eclipsevorto/vorto-generators-3rd-party:latest .;
    docker build --build-arg JAR_FILE=./generator-runner/target/generator-runner-3rd-party-exec.jar -f docker/Generators_Dockerfile -t eclipsevorto/vorto-generators-3rd-party:$TRAVIS_TAG .;
    fi;

deploy:
  provider: script
  script: bash docker/docker_push
  on:
    branch: master
